version: "3"
services:
  server:
    build: ./server
    image: todos-server
    ports: 
      - 4000:4000
    volumes:
      - ./server/src:/usr/src/app/src
  client:
    build: ./client
    image: todos-client
    ports:
      - 3000:3000
    links:
      - server
    volumes:
      - ./client/src:/usr/src/app/src