mutation RemoveTodo($input: RemoveTodoInput!){
  removeTodo(input: $input){
    todo{
      id
      title
      state
    }
    edge{
      node{
        id
        title
        state
      }
    }
  }
}